//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProforgDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public int LG_ID { get; set; }
        public string LG_PASSWORD { get; set; }
        public bool LG_ISADMIN { get; set; }
        public string LG_LOGIN { get; set; }
    }
}
