//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProforgDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_order
    {
        public int order_ID { get; set; }
        public int order_student_ID { get; set; }
        public int order_ticket_ID { get; set; }
        public int order_count { get; set; }
    
        public virtual tab_students tab_students { get; set; }
        public virtual tab_tickets tab_tickets { get; set; }
    }
}
